name: Build

on: workflow_dispatch

jobs:
 build:
   runs-on: [ubuntu-latest]
   steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        
    - uses: actions/checkout@v3
      
    - name: run
      run: |
        make -f Makefile.mingw
    
